### ISSUE TITLE
Cloudflare Workers error: Code generation from strings disallowed for this context

### ISSUE THREAD

**Issue by HelloJowet** [linz/cotar#476]
Hi,

really good work.
Unfortunately I have problems setting up a cotar reader in my environment. I'm using [Cloudflare R2 (S3-compatible)](https://www.cloudflare.com/products/r2/) and [Cloudflare Workers](https://workers.cloudflare.com/) (similar to AWS Lambda).

I successfully created a tar file and indexed it with the cotar cli.
Then I created the cloudflare worker:
```
import { Cotar, CotarIndexBinary } from '@cotar/core';
import { fsa } from '@chunkd/fs'

export interface Env { }

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const source = fsa.source('https://example.com/example.tar.co');
		const cotar = await Cotar.fromTar(source);

		// Fetch a gzipped PBF file from  a tar
		const bytes = await cotar.get(`tiles/z10/5/5.pbf.gz`);

		return new Response(bytes);
	},
};
```

But I'm getting the following error message when I try to execute it:

> service core:user:cotar_test: Uncaught Error: EvalError: Code generation from strings disallowed for this context
  at worker.js:740:18 in generateSingleObject
  at worker.js:730:12 in StrutTypeObjectGenerated
  at worker.js:886:12 in object
  at worker.js:920:20

It seems that it has something to do with the `generateSingleObject` function in the [binparse repo](https://github.com/blacha/binparse/tree/master).

In a [blog post](https://community.cloudflare.com/t/evalerror-code-generation-from-strings-disallowed-for-this-context/356430) I found the following explanation:

> As the error says code generation is not allowed in Functions/Pages. So using eval or new Function is not allowed. This is done for security reasons.

I also tried creating the worker with the [cotar-rs](https://github.com/blacha/cotar-rs) package. But unfortunately http paths aren't implemented yet.

**Comment by blacha** [comment]
Interesting! I didnt know Cloudflare workers prevent `new Function` 

`binparse` uses code generation to increase the speed that objects are parsed from buffers, cotar uses binparse to parse Tar metadata.

As a quick and dirty hack to get something working you can turn off binparse's object generation by adding this before importing `Cotar`

```typescript
import { bp } from 'binparse';
// bp.object is object creation with code generation, bp.static is object creation without code generation
bp.object = bp.static as any;

import {Cotar} from '@cotar/core'
```

Otherwise ill look at removing binparse's object generation from Cotar in the next few days.

**Comment by HelloJowet** [comment]
Hey. Thank you for your fast answer. Unfortunately your suggested quick and dirty hack doesn't work in my case. I still get the same error.

```typescript
import { bp } from 'binparse';
// bp.object is object creation with code generation
// bp.static is object creation without code generation
bp.object = bp.static as any;

import { Cotar } from '@cotar/core';
import { SourceUrl } from '@chunkd/source-url';

export interface Env { }

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const source = new SourceUrl('https://example.com/example.tar.co');
		const cotar = await Cotar.fromTar(source);

		// Fetch a gzipped PBF file from  a tar
		const bytes = await cotar.get(`tiles/z10/5/5.pbf.gz`);

		return new Response(bytes);
	},
};
```

**Comment by HelloJowet** [comment]
Thank you for your answer. With the latest changes, Cotar now works without any errors in Cloudflare Workers. 
It would be great if you could update the npm package with the latest changes. Thank you very much :)
